### ISSUE TITLE
I cant load G-discriminator

### ISSUE THREAD

**Issue by predestined-will** [neka-nat/image_completion_keras#17]
hello,neka-nat!
I am just a bignner. My GPU is low, so i need to load G-discriminator to continue traning. But i can't load G-discriminator like before,It may be caused by the code in line 101,93 of 'mode.py'.I tried some methods that didn't work,So,how do you do it?
Looking forward to your answers..

**Comment by neka-nat** [comment]
Hi @predestined-will ,

Thanks you for reporting.
Can you send me an error message if you'd like?

**Comment by predestined-will** [comment]
Thanks for your reply.


ok.&nbsp;I will show the error message through three pictures.








that's ok? or more error message?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neka-nat/image_completion_tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月7日(星期六) 下午4:09
收件人:&nbsp;"neka-nat/image_completion_tf2"<image_completion_tf2@noreply.github.com&gt;;
抄送:&nbsp;"燕云小郎君"<1244284574@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neka-nat/image_completion_tf2] I cant load G-discriminator (#17)





 
Hi @predestined-will ,
 
Thanks you for reporting.
 Can you send me an error message if you'd like?

**Comment by neka-nat** [comment]
I can't see the images because it doesn't seem to be attached properly.
Can you paste the text?

**Comment by predestined-will** [comment]
ok
This is my code:


def load():
&nbsp;&nbsp;&nbsp; d_model = tf.keras.models.load_model(os.path.join('output\\CNNGAN', 'dis.h5'))
if __name__ == "__main__":
&nbsp;&nbsp;&nbsp; load()


Error Message:


Traceback (most recent call last):
&nbsp; File "D:/ruan_py/CNN-GAN/host.py", line 15, in <module&gt;
&nbsp;&nbsp;&nbsp; load()
&nbsp; File "D:/ruan_py/CNN-GAN/host.py", line 12, in load
&nbsp;&nbsp;&nbsp; d_model = tf.keras.models.load_model(os.path.join('output\\CNNGAN', 'dis.h5'))
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
&nbsp;&nbsp;&nbsp; return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 168, in load_model_from_hdf5
&nbsp;&nbsp;&nbsp; custom_objects=custom_objects)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py", line 55, in model_from_config
&nbsp;&nbsp;&nbsp; return deserialize(config, custom_objects=custom_objects)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py", line 102, in deserialize
&nbsp;&nbsp;&nbsp; printable_module_name='layer')
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py", line 191, in deserialize_keras_object
&nbsp;&nbsp;&nbsp; list(custom_objects.items())))
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 906, in from_config
&nbsp;&nbsp;&nbsp; config, custom_objects)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1852, in reconstruct_from_config
&nbsp;&nbsp;&nbsp; process_node(layer, node_data)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1799, in process_node
&nbsp;&nbsp;&nbsp; output_tensors = layer(input_tensors, **kwargs)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 842, in __call__
&nbsp;&nbsp;&nbsp; outputs = call_fn(cast_inputs, *args, **kwargs)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\layers\core.py", line 795, in call
&nbsp;&nbsp;&nbsp; return self.function(inputs, **arguments)
&nbsp; File "D:/ruan_py/CNN-GAN/model.py", line 103, in <lambda&gt;
&nbsp;&nbsp;&nbsp; cropping = Lambda(lambda x: K.map_fn(lambda y: crop_image(y[0], y[1]), elems=x, dtype=tf.float32),
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\keras\backend.py", line 5804, in map_fn
&nbsp;&nbsp;&nbsp; return map_fn_lib.map_fn(fn, elems, name=name, dtype=dtype)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\ops\map_fn.py", line 268, in map_fn
&nbsp;&nbsp;&nbsp; maximum_iterations=n)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\ops\control_flow_ops.py", line 2675, in while_loop
&nbsp;&nbsp;&nbsp; back_prop=back_prop)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\ops\while_v2.py", line 198, in while_loop
&nbsp;&nbsp;&nbsp; add_control_dependencies=add_control_dependencies)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 915, in func_graph_from_py_func
&nbsp;&nbsp;&nbsp; func_outputs = python_func(*func_args, **func_kwargs)
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\ops\while_v2.py", line 176, in wrapped_body
&nbsp;&nbsp;&nbsp; outputs = body(*_pack_sequence_as(orig_loop_vars, args))
&nbsp; File "D:\software\anaconda\lib\site-packages\tensorflow_core\python\ops\map_fn.py", line 257, in compute
&nbsp;&nbsp;&nbsp; packed_fn_values = fn(packed_values)
&nbsp; File "D:/ruan_py/CNN-GAN/model.py", line 103, in <lambda&gt;
&nbsp;&nbsp;&nbsp; cropping = Lambda(lambda x: K.map_fn(lambda y: crop_image(y[0], y[1]), elems=x, dtype=tf.float32),
TypeError: 'str' object is not callable



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neka-nat/image_completion_tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 晚上10:47
收件人:&nbsp;"neka-nat/image_completion_tf2"<image_completion_tf2@noreply.github.com&gt;;
抄送:&nbsp;"燕云小郎君"<1244284574@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neka-nat/image_completion_tf2] I cant load G-discriminator (#17)





 
I can't see the images because it doesn't seem to be attached properly.
 Can you paste the text?

**Comment by predestined-will** [comment]
Maybe there are some solutions？


What's your version？ my is tf2.0.0.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neka-nat/image_completion_tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 晚上10:47
收件人:&nbsp;"neka-nat/image_completion_tf2"<image_completion_tf2@noreply.github.com&gt;;
抄送:&nbsp;"燕云小郎君"<1244284574@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neka-nat/image_completion_tf2] I cant load G-discriminator (#17)





 
I can't see the images because it doesn't seem to be attached properly.
 Can you paste the text?

**Comment by neka-nat** [comment]
Is 'dis.h5' a parameter file output from the same source code?

**Comment by predestined-will** [comment]
yes, i just 'model_generator()' and model.save() and load


there are code:
discriminator = model_discriminator()
discriminator.summary()
discriminator.save(os.path.join("output\\CNNGAN", "dis.h5"))
# plot_model(discriminator, to_file='discriminator.png', show_shapes=True)

# dis = tf.keras.models.load_model(os.path.join('output\\CNNGAN', 'dis1.h5'))




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "neka-nat/image_completion_tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月19日(星期四) 晚上8:30
收件人:&nbsp;"neka-nat/image_completion_tf2"<image_completion_tf2@noreply.github.com&gt;;
抄送:&nbsp;"燕云小郎君"<1244284574@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neka-nat/image_completion_tf2] I cant load G-discriminator (#17)





 
Is 'dis.h5' a parameter file output from the same source code?
